version: '3.9'

services:
  web:
    build: .
    command: uvicorn XpenseMeter.main:app --reload --port=8000 --host=0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/XpenseMeter
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3